apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ .Release.Name  }}
spec:
   replicas: {{ .Values.replicacount }}
   selector: 
     matchLabels:
       {{- include "match.label" . | nindent 8 }}
   template:
     metadata:
       labels:
         {{- include "match.label" . | nindent 10 }}
     spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port.appport }}

