---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod
  name: req-pod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity: ## to archive affinity use podAffinity, for anti-affinity use podAntiAffinity
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - myapp
        topologyKey: kubernetes.io/hostname
