---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod
  name: req-pod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cpu
            operator: NotIn # for affinity user IN , for Anti-Affinity use NotIn
            values:
            - ryzen
          
