apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: splunk
spec:
   selector: 
     matchLabels:
       app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: node-role.kubernetes.io/control-plane
#    operator: "Equal"
        effect: NoSchedule

