apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydep
spec:
   replicas: 3
   selector: 
     matchLabels:
       app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
      containers:
      - name: con1
        image: nginx
        ports:
        - containerPort: 80
