apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins-limit
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: "512Mi"
    defaultRequest: # this section defines default requests
      cpu: 80m
      memory: "64Mi"
    type: Container
