---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mydb
  name: mydb
spec:
  containers:
  - image: mysql:5.7
    name: con1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbpass
          key: password 
    - name: MYSQL_DATABASE
      value: wpdb

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  selector:
    app:  mydb
  ports:
  - port: 3306
    targetPort: 3306

