---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod
  name: nodeselc-pod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
  nodeSelector: 
    cpu: ryzen

