---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
    env: dev
  name: liv-tcp
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
         port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  - image: tomcat:latest
    name: con2
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123

