---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
    env: dev
  name: mypod
spec:
  serviceAccount: robo
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123

