apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: pvc-pod
spec:
  containers:
  - image: nginx
    name: mypod
    volumeMounts:
    - name: myvol
      mountPath: /data
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: mypvc 
