apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
      - containerPort: 80
    resources:
      requests:
         cpu: "100m"
         memory: "128Mi"
      limits:
        memory: "512Mi"
        cpu: "500m"
  - name: con2
    image: tomcat:latest
    ports:
      - containerPort: 8080

