apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: janeesh
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: janeesh
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: aneesh

# kubectl -n jenkins create rolebinding janeesh --user aneesh --role janeesh --dry-run=client -o yaml > role-binding.yaml
