apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: janeesh
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - create
  - edit
  - get
  - list
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - edit
  - get
  - list
  - delete

#kubectl create role janeesh --resource pod,deployment,configmap --verb create,edit,get,list,delete --dry-run=client -o yaml > role.yaml

