---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress-2
  name: wordpress-2
spec:
  containers:
  - image: wordpress:latest
    name: con1
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-svc
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: test123
    - name: WORDPRESS_DB_NAME
      value: wpdb
    - name: WORDPRESS_TABLE_PREFIX
      value: wp2_ 
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc-2
spec:
  type: NodePort
  selector:
    app: wordpress-2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30125

